
skillMetadata:
  sections:
      name: Select Region
        fields:
          - name: my_selected_option
            type: select
            label: Select an option
            options: England|option_one;Other place|option_two;Yet another place|option_three
            value: option_one
    - name: Login << Name of another section
      fields:
        - type: label
          label: Just a little bit of extra info for the user to understand following settings
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
