
skillMetadata:
  sections:
      name: Select Region
        fields:
          - name: my_selected_option
            type: select
            label: Select an option
            options: England|option_one;Other place|option_two;Yet another place|option_three
            value: option_one
