
skillMetadata:
  sections:
    - name: Select Region 
      fields:
        - name: regionSelectValue
          type: select
          label: Please choose the region you want carbon data for
          value: 1
          placeholder: England
    - name: Login << Name of another section
      fields:
        - type: label
          label: Just a little bit of extra info for the user to understand following settings
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
